apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: "Testing"
    tekton.dev/tags: echo
    tekton.dev/displayName: "echo"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  params:
    - name: appName
      default: ''
  steps:
    - image: quay.io/fedora/fedora:38
      command:
        - /bin/bash
        - '-c'
        - echo
        - $(inputs.params.appName)
